/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentKeyDetailsV1 {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Box<crate::models::ContentKeyV1>>,
    #[serde(rename = "mergeBehavior", skip_serializing_if = "Option::is_none")]
    pub merge_behavior: Option<crate::models::MergeBehaviorV1>,
}

impl ContentKeyDetailsV1 {
    pub fn new() -> ContentKeyDetailsV1 {
        ContentKeyDetailsV1 {
            key: None,
            merge_behavior: None,
        }
    }
}


