/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentWithKeyV2 {
    #[serde(rename = "key")]
    pub key: Box<crate::models::ContentKeyV2>,
    #[serde(rename = "content")]
    pub content: Box<crate::models::ContentV2>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<Box<crate::models::DocumentationV2>>,
}

impl ContentWithKeyV2 {
    pub fn new(key: crate::models::ContentKeyV2, content: crate::models::ContentV2) -> ContentWithKeyV2 {
        ContentWithKeyV2 {
            key: Box::new(key),
            content: Box::new(content),
            documentation: None,
        }
    }
}


