/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentResponseV2 {
    #[serde(rename = "content")]
    pub content: Box<crate::models::ContentV2>,
    #[serde(rename = "effectiveReference", skip_serializing_if = "Option::is_none")]
    pub effective_reference: Option<Box<crate::models::ReferenceV2>>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<Box<crate::models::DocumentationV2>>,
}

impl ContentResponseV2 {
    pub fn new(content: crate::models::ContentV2) -> ContentResponseV2 {
        ContentResponseV2 {
            content: Box::new(content),
            effective_reference: None,
            documentation: None,
        }
    }
}


