/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentWithKey {
    #[serde(rename = "key")]
    pub key: Box<crate::models::ContentKey>,
    #[serde(rename = "content")]
    pub content: Box<crate::models::Content>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<Box<crate::models::Documentation>>,
}

impl ContentWithKey {
    pub fn new(key: crate::models::ContentKey, content: crate::models::Content) -> ContentWithKey {
        ContentWithKey {
            key: Box::new(key),
            content: Box::new(content),
            documentation: None,
        }
    }
}


