/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DiffEntryV1 {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Box<crate::models::ContentKeyV1>>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<Box<crate::models::ContentV1>>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<Box<crate::models::ContentV1>>,
}

impl DiffEntryV1 {
    pub fn new() -> DiffEntryV1 {
        DiffEntryV1 {
            key: None,
            from: None,
            to: None,
        }
    }
}


