/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Documentation {
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    #[serde(rename = "text")]
    pub text: String,
}

impl Documentation {
    pub fn new(mime_type: String, text: String) -> Documentation {
        Documentation {
            mime_type,
            text,
        }
    }
}


