/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EntriesResponseV2 {
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "entries")]
    pub entries: Vec<crate::models::EntryV2>,
    #[serde(rename = "effectiveReference", skip_serializing_if = "Option::is_none")]
    pub effective_reference: Option<Box<crate::models::ReferenceV2>>,
}

impl EntriesResponseV2 {
    pub fn new(entries: Vec<crate::models::EntryV2>) -> EntriesResponseV2 {
        EntriesResponseV2 {
            has_more: None,
            token: None,
            entries,
            effective_reference: None,
        }
    }
}


