/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EntriesResponseV1 {
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "entries")]
    pub entries: Vec<crate::models::EntryV1>,
}

impl EntriesResponseV1 {
    pub fn new(entries: Vec<crate::models::EntryV1>) -> EntriesResponseV1 {
        EntriesResponseV1 {
            has_more: None,
            token: None,
            entries,
        }
    }
}


