/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FetchOption {
    #[serde(rename = "MINIMAL")]
    Minimal,
    #[serde(rename = "ALL")]
    All,

}

impl ToString for FetchOption {
    fn to_string(&self) -> String {
        match self {
            Self::Minimal => String::from("MINIMAL"),
            Self::All => String::from("ALL"),
        }
    }
}

impl Default for FetchOption {
    fn default() -> FetchOption {
        Self::Minimal
    }
}




