/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMultipleContentsResponseV2 {
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::ContentWithKeyV2>,
    #[serde(rename = "effectiveReference", skip_serializing_if = "Option::is_none")]
    pub effective_reference: Option<Box<crate::models::ReferenceV2>>,
}

impl GetMultipleContentsResponseV2 {
    pub fn new(contents: Vec<crate::models::ContentWithKeyV2>) -> GetMultipleContentsResponseV2 {
        GetMultipleContentsResponseV2 {
            contents,
            effective_reference: None,
        }
    }
}


