/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMultipleContentsResponse {
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::ContentWithKey>,
    #[serde(rename = "effectiveReference", skip_serializing_if = "Option::is_none")]
    pub effective_reference: Option<Box<crate::models::Reference>>,
}

impl GetMultipleContentsResponse {
    pub fn new(contents: Vec<crate::models::ContentWithKey>) -> GetMultipleContentsResponse {
        GetMultipleContentsResponse {
            contents,
            effective_reference: None,
        }
    }
}


