/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMultipleContentsResponseV1 {
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::ContentWithKeyV1>,
}

impl GetMultipleContentsResponseV1 {
    pub fn new(contents: Vec<crate::models::ContentWithKeyV1>) -> GetMultipleContentsResponseV1 {
        GetMultipleContentsResponseV1 {
            contents,
        }
    }
}


