/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMultipleContentsRequest {
    #[serde(rename = "requestedKeys")]
    pub requested_keys: Vec<crate::models::ContentKey>,
}

impl GetMultipleContentsRequest {
    pub fn new(requested_keys: Vec<crate::models::ContentKey>) -> GetMultipleContentsRequest {
        GetMultipleContentsRequest {
            requested_keys,
        }
    }
}


