/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IcebergTable : Represents the state of an Iceberg table in Nessie. An Iceberg table is globally identified via its unique 'Content.id'.  A Nessie commit-operation, performed via 'TreeApi.commitMultipleOperations',for Iceberg consists of a 'Operation.Put' with an 'IcebergTable' as in the 'content' field and the previous value of 'IcebergTable' in the 'expectedContent' field.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IcebergTable {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "metadataLocation")]
    pub metadata_location: String,
    #[serde(rename = "snapshotId", skip_serializing_if = "Option::is_none")]
    pub snapshot_id: Option<i64>,
    #[serde(rename = "schemaId", skip_serializing_if = "Option::is_none")]
    pub schema_id: Option<i32>,
    #[serde(rename = "specId", skip_serializing_if = "Option::is_none")]
    pub spec_id: Option<i32>,
    #[serde(rename = "sortOrderId", skip_serializing_if = "Option::is_none")]
    pub sort_order_id: Option<i32>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl IcebergTable {
    /// Represents the state of an Iceberg table in Nessie. An Iceberg table is globally identified via its unique 'Content.id'.  A Nessie commit-operation, performed via 'TreeApi.commitMultipleOperations',for Iceberg consists of a 'Operation.Put' with an 'IcebergTable' as in the 'content' field and the previous value of 'IcebergTable' in the 'expectedContent' field.
    pub fn new(metadata_location: String) -> IcebergTable {
        IcebergTable {
            id: None,
            metadata_location,
            snapshot_id: None,
            schema_id: None,
            spec_id: None,
            sort_order_id: None,
            metadata: None,
        }
    }
}


