/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogEntryV1 {
    #[serde(rename = "commitMeta")]
    pub commit_meta: Box<crate::models::CommitMetaV1>,
    #[serde(rename = "additionalParents", skip_serializing_if = "Option::is_none")]
    pub additional_parents: Option<Vec<String>>,
    #[serde(rename = "parentCommitHash", skip_serializing_if = "Option::is_none")]
    pub parent_commit_hash: Option<String>,
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Vec<crate::models::OperationV1>>,
}

impl LogEntryV1 {
    pub fn new(commit_meta: crate::models::CommitMetaV1) -> LogEntryV1 {
        LogEntryV1 {
            commit_meta: Box::new(commit_meta),
            additional_parents: None,
            parent_commit_hash: None,
            operations: None,
        }
    }
}


