/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogResponse {
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "logEntries")]
    pub log_entries: Vec<crate::models::LogEntry>,
}

impl LogResponse {
    pub fn new(log_entries: Vec<crate::models::LogEntry>) -> LogResponse {
        LogResponse {
            has_more: None,
            token: None,
            log_entries,
        }
    }
}


