/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MergeBehaviorV2 {
    #[serde(rename = "NORMAL")]
    Normal,
    #[serde(rename = "FORCE")]
    Force,
    #[serde(rename = "DROP")]
    Drop,

}

impl ToString for MergeBehaviorV2 {
    fn to_string(&self) -> String {
        match self {
            Self::Normal => String::from("NORMAL"),
            Self::Force => String::from("FORCE"),
            Self::Drop => String::from("DROP"),
        }
    }
}

impl Default for MergeBehaviorV2 {
    fn default() -> MergeBehaviorV2 {
        Self::Normal
    }
}




