/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NamespaceUpdate {
    #[serde(rename = "propertyUpdates", skip_serializing_if = "Option::is_none")]
    pub property_updates: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "propertyRemovals", skip_serializing_if = "Option::is_none")]
    pub property_removals: Option<Vec<String>>,
}

impl NamespaceUpdate {
    pub fn new() -> NamespaceUpdate {
        NamespaceUpdate {
            property_updates: None,
            property_removals: None,
        }
    }
}


