/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Namespace {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "elements")]
    pub elements: Vec<String>,
    #[serde(rename = "properties")]
    pub properties: ::std::collections::HashMap<String, String>,
}

impl Namespace {
    pub fn new(elements: Vec<String>, properties: ::std::collections::HashMap<String, String>) -> Namespace {
        Namespace {
            id: None,
            elements,
            properties,
        }
    }
}


