/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Operation : Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum Operation {
    #[serde(rename="DELETE")]
    Delete {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKey>,
    },
    #[serde(rename="PUT")]
    Put {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKey>,
        #[serde(rename = "content")]
        content: Box<crate::models::Content>,
        #[serde(rename = "expectedContent", skip_serializing_if = "Option::is_none")]
        expected_content: Option<Box<crate::models::PutExpectedContent>>,
        #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
        metadata: Option<Vec<crate::models::ContentMetadata>>,
        #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
        documentation: Option<Box<crate::models::Documentation>>,
    },
    #[serde(rename="UNCHANGED")]
    Unchanged {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKey>,
    },
}




