/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Operations {
    #[serde(rename = "commitMeta")]
    pub commit_meta: Box<crate::models::CommitMeta>,
    #[serde(rename = "operations")]
    pub operations: Vec<crate::models::Operation>,
}

impl Operations {
    pub fn new(commit_meta: crate::models::CommitMeta, operations: Vec<crate::models::Operation>) -> Operations {
        Operations {
            commit_meta: Box::new(commit_meta),
            operations,
        }
    }
}


