/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OperationV1 : Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum OperationV1 {
    #[serde(rename="DELETE")]
    DeleteV1 {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKeyV1>,
    },
    #[serde(rename="PUT")]
    PutV1 {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKeyV1>,
        #[serde(rename = "content")]
        content: Box<crate::models::ContentV1>,
        #[serde(rename = "expectedContent", skip_serializing_if = "Option::is_none")]
        expected_content: Option<Box<crate::models::PutV1ExpectedContent>>,
    },
    #[serde(rename="UNCHANGED")]
    UnchangedV1 {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKeyV1>,
    },
}




