/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// OperationV2 : Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OperationV2 {
    #[serde(rename = "DELETE")]
    DeleteV2 {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKeyV2>,
    },
    #[serde(rename = "PUT")]
    PutV2 {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKeyV2>,
        #[serde(rename = "content")]
        content: Box<crate::models::ContentV2>,
        #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
        metadata: Option<Vec<crate::models::ContentMetadataV2>>,
        #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
        documentation: Option<Box<crate::models::DocumentationV2>>,
    },
    #[serde(rename = "UNCHANGED")]
    UnchangedV2 {
        #[serde(rename = "key")]
        key: Box<crate::models::ContentKeyV2>,
    },
}
