/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutExpectedContent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "metadataLocation")]
    pub metadata_location: String,
    #[serde(rename = "snapshotId", skip_serializing_if = "Option::is_none")]
    pub snapshot_id: Option<i64>,
    #[serde(rename = "schemaId", skip_serializing_if = "Option::is_none")]
    pub schema_id: Option<i32>,
    #[serde(rename = "specId", skip_serializing_if = "Option::is_none")]
    pub spec_id: Option<i32>,
    #[serde(rename = "sortOrderId", skip_serializing_if = "Option::is_none")]
    pub sort_order_id: Option<i32>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "metadataLocationHistory")]
    pub metadata_location_history: Vec<String>,
    #[serde(rename = "checkpointLocationHistory")]
    pub checkpoint_location_history: Vec<String>,
    #[serde(rename = "lastCheckpoint", skip_serializing_if = "Option::is_none")]
    pub last_checkpoint: Option<String>,
    #[serde(rename = "versionId", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<i64>,
    #[serde(rename = "sqlText")]
    pub sql_text: String,
    #[serde(rename = "dialect", skip_serializing_if = "Option::is_none")]
    pub dialect: Option<String>,
    #[serde(rename = "elements")]
    pub elements: Vec<String>,
    #[serde(rename = "properties")]
    pub properties: ::std::collections::HashMap<String, String>,
}

impl PutExpectedContent {
    pub fn new(metadata_location: String, metadata_location_history: Vec<String>, checkpoint_location_history: Vec<String>, sql_text: String, elements: Vec<String>, properties: ::std::collections::HashMap<String, String>) -> PutExpectedContent {
        PutExpectedContent {
            id: None,
            metadata_location,
            snapshot_id: None,
            schema_id: None,
            spec_id: None,
            sort_order_id: None,
            metadata: None,
            metadata_location_history,
            checkpoint_location_history,
            last_checkpoint: None,
            version_id: None,
            sql_text,
            dialect: None,
            elements,
            properties,
        }
    }
}


