/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReferenceCutoffPolicyV2 : Cutoff policies per reference names. Supplied as a ref-name-pattern=policy tuple. Reference name patterns are regular expressions.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReferenceCutoffPolicyV2 {
    /// Reference name patterns as a regular expressions.
    #[serde(rename = "referenceNamePattern", skip_serializing_if = "Option::is_none")]
    pub reference_name_pattern: Option<String>,
    /// Policies can be one of: - number of commits as an integer value - a duration (see java.time.Duration) - an ISO instant - 'NONE', means everything's considered as live
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
}

impl ReferenceCutoffPolicyV2 {
    /// Cutoff policies per reference names. Supplied as a ref-name-pattern=policy tuple. Reference name patterns are regular expressions.
    pub fn new() -> ReferenceCutoffPolicyV2 {
        ReferenceCutoffPolicyV2 {
            reference_name_pattern: None,
            policy: None,
        }
    }
}


