/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum Reference {
    #[serde(rename="BRANCH")]
    Branch {
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
        metadata: Option<Box<crate::models::ReferenceMetadata>>,
        #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
        hash: Option<String>,
    },
    #[serde(rename="DETACHED")]
    Detached {
        #[serde(rename = "hash")]
        hash: String,
        #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
        metadata: Option<Box<crate::models::ReferenceMetadata>>,
    },
    #[serde(rename="TAG")]
    Tag {
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
        metadata: Option<Box<crate::models::ReferenceMetadata>>,
        #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
        hash: Option<String>,
    },
}




