/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReferenceType {
    #[serde(rename = "branch")]
    Branch,
    #[serde(rename = "tag")]
    Tag,

}

impl ToString for ReferenceType {
    fn to_string(&self) -> String {
        match self {
            Self::Branch => String::from("branch"),
            Self::Tag => String::from("tag"),
        }
    }
}

impl Default for ReferenceType {
    fn default() -> ReferenceType {
        Self::Branch
    }
}




