/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReferenceMetadataV1 : Only returned by the server when explicitly requested by the client and contains the following information:  - numCommitsAhead (number of commits ahead of the default branch)  - numCommitsBehind (number of commits behind the default branch)  - commitMetaOfHEAD (the commit metadata of the HEAD commit)  - commonAncestorHash (the hash of the common ancestor in relation to the default branch).  - numTotalCommits (the total number of commits in this reference).  



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReferenceMetadataV1 {
    #[serde(rename = "numCommitsAhead", skip_serializing_if = "Option::is_none")]
    pub num_commits_ahead: Option<i32>,
    #[serde(rename = "numCommitsBehind", skip_serializing_if = "Option::is_none")]
    pub num_commits_behind: Option<i32>,
    #[serde(rename = "commitMetaOfHEAD", skip_serializing_if = "Option::is_none")]
    pub commit_meta_of_head: Option<Box<crate::models::CommitMetaV1>>,
    #[serde(rename = "commonAncestorHash", skip_serializing_if = "Option::is_none")]
    pub common_ancestor_hash: Option<String>,
    #[serde(rename = "numTotalCommits", skip_serializing_if = "Option::is_none")]
    pub num_total_commits: Option<i64>,
}

impl ReferenceMetadataV1 {
    /// Only returned by the server when explicitly requested by the client and contains the following information:  - numCommitsAhead (number of commits ahead of the default branch)  - numCommitsBehind (number of commits behind the default branch)  - commitMetaOfHEAD (the commit metadata of the HEAD commit)  - commonAncestorHash (the hash of the common ancestor in relation to the default branch).  - numTotalCommits (the total number of commits in this reference).  
    pub fn new() -> ReferenceMetadataV1 {
        ReferenceMetadataV1 {
            num_commits_ahead: None,
            num_commits_behind: None,
            commit_meta_of_head: None,
            common_ancestor_hash: None,
            num_total_commits: None,
        }
    }
}


