/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "r#type")]
pub enum RepositoryConfig {
    #[serde(rename="GARBAGE_COLLECTOR")]
    GarbageCollectorConfig {
        /// The default cutoff policy. Policies can be one of: - number of commits as an integer value - a duration (see java.time.Duration) - an ISO instant - 'NONE', means everything's considered as live
        #[serde(rename = "defaultCutoffPolicy", skip_serializing_if = "Option::is_none")]
        default_cutoff_policy: Option<String>,
        #[serde(rename = "perRefCutoffPolicies", skip_serializing_if = "Option::is_none")]
        per_ref_cutoff_policies: Option<Vec<crate::models::ReferenceCutoffPolicy>>,
        /// Files that have been created after 'gc-start-time - new-files-grace-period' are not being deleted.
        #[serde(rename = "newFilesGracePeriod", skip_serializing_if = "Option::is_none")]
        new_files_grace_period: Option<String>,
        #[serde(rename = "expectedFileCountPerContent", skip_serializing_if = "Option::is_none")]
        expected_file_count_per_content: Option<i32>,
    },
}




