/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RepositoryConfigurationObjectsForTheRequestedTypes : The existing configuration objects for the requested types will be returned. Non-existing config objects will not be returned.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepositoryConfigurationObjectsForTheRequestedTypes {
    /// The existing configuration objects for the requested types will be returned. Non-existing config objects will not be returned.
    #[serde(rename = "configs", skip_serializing_if = "Option::is_none")]
    pub configs: Option<Vec<crate::models::RepositoryConfigV2>>,
}

impl RepositoryConfigurationObjectsForTheRequestedTypes {
    /// The existing configuration objects for the requested types will be returned. Non-existing config objects will not be returned.
    pub fn new() -> RepositoryConfigurationObjectsForTheRequestedTypes {
        RepositoryConfigurationObjectsForTheRequestedTypes {
            configs: None,
        }
    }
}


