/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SingleReferenceResponseV2 {
    #[serde(rename = "reference")]
    pub reference: Box<crate::models::ReferenceV2>,
}

impl SingleReferenceResponseV2 {
    pub fn new(reference: crate::models::ReferenceV2) -> SingleReferenceResponseV2 {
        SingleReferenceResponseV2 {
            reference: Box::new(reference),
        }
    }
}
