/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ThePreviousStateOfTheRepositoryConfigurationObject : When a repository configuration for the same type as in the request object did not exist, the response object will be null. Otherwise, if the configuration was updated, the old value will be returned.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ThePreviousStateOfTheRepositoryConfigurationObject {
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<Box<crate::models::ThePreviousStateOfTheRepositoryConfigurationObject>>,
}

impl ThePreviousStateOfTheRepositoryConfigurationObject {
    /// When a repository configuration for the same type as in the request object did not exist, the response object will be null. Otherwise, if the configuration was updated, the old value will be returned.
    pub fn new() -> ThePreviousStateOfTheRepositoryConfigurationObject {
        ThePreviousStateOfTheRepositoryConfigurationObject {
            previous: None,
        }
    }
}


