/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Unchanged {
    #[serde(rename = "key")]
    pub key: Box<crate::models::ContentKey>,
}

impl Unchanged {
    pub fn new(key: crate::models::ContentKey) -> Unchanged {
        Unchanged {
            key: Box::new(key),
        }
    }
}


