/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateRepositoryConfigResponse {
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<Box<crate::models::ThePreviousStateOfTheRepositoryConfigurationObject1>>,
}

impl UpdateRepositoryConfigResponse {
    pub fn new() -> UpdateRepositoryConfigResponse {
        UpdateRepositoryConfigResponse {
            previous: None,
        }
    }
}


