/*
 * Nessie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateRepositoryConfigRequest {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<crate::models::RepositoryConfig>>,
}

impl UpdateRepositoryConfigRequest {
    pub fn new() -> UpdateRepositoryConfigRequest {
        UpdateRepositoryConfigRequest {
            config: None,
        }
    }
}


